spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/mini_story?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kmhmh103099~
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#springdoc:
#  version: v1.0.0
#  packages-to-scan: com.example.swagger3test
#  swagger-ui:
#    path: /swagger
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /api-docs
#    groups:
#      enabled: true
#  cache:
#    disabled: true
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
springfox:
  documenration:
    swagger:
      use-model-v3: false

logging:
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.example: debug

server:
  port: 8080